### ISSUE TITLE
Unable to run plugin with Elasticsearch 2.0

### ISSUE THREAD

**Issue by prashanttct07** [mobz/elasticsearch-head#211]
Hi

I installed ES 2.0, and then head plugin.

So while opening the URL localhost:9200/_plugin/head , I am not able to get the details and ES is showing the exceptions as : 
```
[2015-10-29 14:31:06,783][INFO ][rest.suppressed          ] /_status Params: {index=_status}
java.lang.IllegalArgumentException: No feature for name [_status]
        at org.elasticsearch.action.admin.indices.get.GetIndexRequest$Feature.fromName(GetIndexRequest.java:82)
        at org.elasticsearch.action.admin.indices.get.GetIndexRequest$Feature.convertToFeatures(GetIndexRequest.java:95)
        at org.elasticsearch.rest.action.admin.indices.get.RestGetIndicesAction.handleRequest(RestGetIndicesAction.java:77)
        at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:54)
        at org.elasticsearch.rest.RestController.executeHandler(RestController.java:207)
        at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:166)
        at org.elasticsearch.http.HttpServer.internalDispatchRequest(HttpServer.java:128)
        at org.elasticsearch.http.HttpServer$Dispatcher.dispatchRequest(HttpServer.java:86)
        at org.elasticsearch.http.netty.NettyHttpServerTransport.dispatchRequest(NettyHttpServerTransport.java:348)
        at org.elasticsearch.http.netty.HttpRequestHandler.messageReceived(HttpRequestHandler.java:63)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.http.netty.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:60)
        at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

Kindly let me know what to do for same.

**Comment by zjzcn** [comment]
+1

**Comment by EamonZhang** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/2.0/indices-status.html
say The index _status API has been replaced with the Indices Stats and Indices Recovery APIs.

**Comment by tmatei** [comment]
Please fix this.

**Comment by yiyuqiuchi** [comment]
+1

**Comment by fosron** [comment]
+1

**Comment by francesco-coletta** [comment]
+1

**Comment by marcinkubica** [comment]
+1
been using head on a daily basis, and now ohnoes! ;-)

**Comment by HenleyChiu** [comment]
+1

**Comment by konste** [comment]
+1

**Comment by claygorman** [comment]
+1

**Comment by rostiar** [comment]
+1

**Comment by zhangzk** [comment]
+1

**Comment by redtopia** [comment]
+2

**Comment by harpreetsb** [comment]
+1

**Comment by zhixiao-kooboo** [comment]
+1

**Comment by adriankirchner** [comment]
+1

**Comment by narakg** [comment]
+1

**Comment by ebuildy** [comment]
I have made a quick fix, https://github.com/mobz/elasticsearch-head/pull/212, this should work.

**Comment by redtopia** [comment]
How do you install the fix?

**Comment by konste** [comment]
It is not integrated into the main branch yet, but this worked for me:

plugin install ebuildy/elasticsearch-head

**Comment by redtopia** [comment]
Ehhh... just a partial fix. Overview works, but nothing else does.

**Comment by ebuildy** [comment]
Yep ;-( took me just a few minutes, but I will do a better thing later.

Also, I am discussing with some friends here to organize a small hackaton in order to make a superbe ES web UI, with some features:
- cluster overview
- analysis tester (from http://es.subitolabs.com/#/)
- documents browser
- query builder
- sense

We are located in south France, all help is welcomed ;-)

**Comment by remyderuysscher** [comment]
Those features sound exactly like kopf!

https://github.com/lmenezes/elasticsearch-kopf

I find the query builder with sense support very helpfull!

On Mon, Nov 2, 2015 at 6:54 PM, Thomas Decaux <notifications@github.com>
wrote:

> Yep ;-( took me just a few minutes, but I will do a better thing later.
>
> Also, I am discussing with some friends here to organize a small hackaton
> in order to make a superbe ES web UI, with some features:
>
>    - cluster overview
>    - analysis tester (from http://es.subitolabs.com/#/)
>    - documents browser
>    - query builder
>    - sense
>
> We are located in south France, all help is welcomed ;-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mobz/elasticsearch-head/issues/211#issuecomment-153099523>
> .
>



-- 

Met vriendelijke groet / with kind regards,
Remy de Ruysscher

remy@unix-asp.com (MOBIEL NUMMER: 06-28184781)

**Comment by FrnkVieira** [comment]
ebuildy, i would love to help because i don't like the existent interfaces (including kopf!).

**Comment by HenleyChiu** [comment]
Thanks @ebuildy - it's a partial fix, but seeing the green shards was all I wanted to see. The browser, etc would be nice, but those are dangerous to access in production so it's OK that doesn't work :)

**Comment by ryanchou1991** [comment]
+1 I have same issue. Have it fixed?

**Comment by harpreetsb** [comment]
@ryanchou1991 no its not fixed. it partial fix,  browser tab does not work.

**Comment by ryanchou1991** [comment]
@harpreetsb OK, I got the issue as you said. I hope it could be fixed soon. because Head was one of my favorite plugins : )

**Comment by shaohuaniu** [comment]
+

**Comment by shaohuaniu** [comment]
+1

**Comment by FrnkVieira** [comment]
+1

**Comment by philipskokoh** [comment]
I fixed more breaking errors at quick menu, indices overview tab, and structured query tab.
#218 should work.

**Comment by ryanchou1991** [comment]
:+1:

**Comment by konste** [comment]
Er... how we install it?

**Comment by Ardoise** [comment]
+1

**Comment by Den3** [comment]
+1

**Comment by philipskokoh** [comment]
@konste: It's not integrated to the main branch yet.
plugin install philipskokoh/elasticsearch-head/ES2-support

**Comment by trentcioran** [comment]
+1

**Comment by klein0r** [comment]
+1

**Comment by rlam3** [comment]
+1
