### ISSUE TITLE
es5.0.0 install error

### ISSUE THREAD

**Issue by Turing-Chu** [mobz/elasticsearch-head#262]
## I can not find a plugin command in elasticsearch-5.0.0-alpha3/bin but a elasticsearch-plugin command can install plugins
* OS: OS X EI Caption  10.11.3
* es source: https://www.elastic.co/downloads/elasticsearch
* es plugin:
```
[ root@XXXX: bin ]$ ./elasticsearch-plugin -h
A tool for managing installed elasticsearch plugins

Commands
--------
list - Lists installed elasticsearch plugins
install - Install a plugin
remove - Removes a plugin from elasticsearch

Non-option arguments:
command              

Option         Description        
------         -----------        
-h, --help     show help          
-s, --silent   show minimal output
-v, --verbose  show verbose output
```
* error info
```
[ root@XXXX: bin ]$ ./elasticsearch-plugin install mobz/elasticsearch-head
-> Downloading mobz/elasticsearch-head
Exception in thread "main" java.net.MalformedURLException: no protocol: mobz/elasticsearch-head
	at java.net.URL.<init>(URL.java:593)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at org.elasticsearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:247)
	at org.elasticsearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:241)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:201)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:189)
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:91)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:91)
	at org.elasticsearch.cli.Command.main(Command.java:53)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:61)
```

**Comment by philipskokoh** [comment]
Site plugin is not supported anymore in Elasticsearch-5.0.0
https://github.com/elastic/elasticsearch/issues/17708

I suggest you run Elasticsearc-head as a standalone server
https://github.com/mobz/elasticsearch-head#running-with-built-in-server
