### ISSUE TITLE
unable to run standalone server on Ubuntu 16.04.1 LTS

### ISSUE THREAD

**Issue by amlife** [mobz/elasticsearch-head#287]
```
# cat /etc/issue
Ubuntu 16.04.1 LTS \n \l
```

- node v6.9.1
- v3.10.8

Here is my install log
```
# npm install

> phantomjs-prebuilt@2.1.13 install /root/elasticsearch-head/node_modules/phantomjs-prebuilt
> node install.js

module.js:471
    throw err;
    ^

Error: Cannot find module '/root/elasticsearch-head/node_modules/phantomjs-prebuilt/install.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
elasticsearch-head@0.0.0 /root/elasticsearch-head
└── (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN elasticsearch-head@0.0.0 license should be a valid SPDX license expression
npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.13 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.13 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/elasticsearch-head/npm-debug.log
npm ERR! code 1
```

Now, npm-debug.log is huge, here is a pastebin [http://pastebin.com/raw/ZvdVFWUM ]( http://pastebin.com/raw/ZvdVFWUM)

**Comment by mobz** [comment]
looks like you might have some npm modules installed as root? `sudo npm install` might solve the problem, but it's more secure if your entire node stack runs without root.  Let me know

**Comment by mobz** [comment]
```7633 silly install phantomjs-prebuilt@2.1.13 /root/elasticsearch-head/node_modules/.staging/phantomjs-prebuilt-8103e936
7634 info lifecycle phantomjs-prebuilt@2.1.13~install: phantomjs-prebuilt@2.1.13
7635 verbose lifecycle phantomjs-prebuilt@2.1.13~install: unsafe-perm in lifecycle false
7636 verbose lifecycle phantomjs-prebuilt@2.1.13~install: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/root/elasticsearch-head/node_modules/phantomjs-prebuilt/node_modules/.bin:/root/elasticsearch-head/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/snap/bin
7637 verbose lifecycle phantomjs-prebuilt@2.1.13~install: CWD: /root/elasticsearch-head/node_modules/phantomjs-prebuilt
7638 silly lifecycle phantomjs-prebuilt@2.1.13~install: Args: [ '-c', 'node install.js' ]
7639 silly lifecycle phantomjs-prebuilt@2.1.13~install: Returned: code: 1  signal: null
7640 info lifecycle phantomjs-prebuilt@2.1.13~install: Failed to exec install script
```
this is the bit that failed, so perhaps type `cd node_modules/phantomjs_prebuilt && sh -c node install.js` which is what it's trying to do
