### ISSUE TITLE
MAC os  "PhantomJS Downloading" there is an Error IN "npm install"

### ISSUE THREAD

**Issue by linfanli** [mobz/elasticsearch-head#323]
`Running` with built in server`
can't download the PhantomJS , because the url as follow is update
https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-macosx.zip

the log shows as 
`PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-macosx.zip
Saving to /var/folders/vm/jfxwkkxx38dfg93nyt6yv3gxfk5vqk/T/phantomjs/phantomjs-2.1.1-macosx.zip
Receiving...
       
Error making request.
Error: read ETIMEDOUT
    at exports._errnoException (util.js:1033:11)
    at TLSWrap.onread (net.js:584:26)

Please report this full log at https://github.com/Medium/phantomjs`

**Comment by linfanli** [comment]
net problem
