### ISSUE TITLE
npm ERR! phantomjs-prebuilt@2.1.14 install: `node install.js`

### ISSUE THREAD

**Issue by bmcgair** [mobz/elasticsearch-head#330]
npm ERR! Linux 3.13.0-116-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.14 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.14 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.

**Comment by francoisfernando** [comment]
I get same error in AWS Ubuntu 16.04 LTS AMI
npm ERR! phantomjs-prebuilt@2.1.14 install: `node install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.14 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

**Comment by jmreymond** [comment]
same issue with Ubuntu 17.04 :-(

> 6010 warn optional Skipping failed optional dependency /chokidar/fsevents:
6011 warn notsup Not compatible with your operating system or architecture: fsevents@1.1.2
6012 warn elasticsearch-head@0.0.0 license should be a valid SPDX license expression
6013 verbose stack Error: phantomjs-prebuilt@2.1.15 install: `node install.js`
6013 verbose stack spawn ENOENT
6013 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
6013 verbose stack     at emitTwo (events.js:87:13)
6013 verbose stack     at ChildProcess.emit (events.js:172:7)
6013 verbose stack     at maybeClose (internal/child_process.js:854:16)
6013 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
6014 verbose pkgid phantomjs-prebuilt@2.1.15
6015 verbose cwd /home/jmax/Projets/Elasticsearch-head/elasticsearch-head-master
6016 error Linux 4.10.0-33-generic
6017 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
6018 error node v4.7.2
6019 error npm  v3.5.2
6020 error file sh
6021 error code ELIFECYCLE
6022 error errno ENOENT
6023 error syscall spawn
6024 error phantomjs-prebuilt@2.1.15 install: `node install.js`
6024 error spawn ENOENT
6025 error Failed at the phantomjs-prebuilt@2.1.15 install script 'node install.js'.
6025 error Make sure you have the latest version of node.js and npm installed.
6025 error If you do, this is most likely a problem with the phantomjs-prebuilt package,
6025 error not with npm itself.
6025 error Tell the author that this fails on your system:
6025 error     node install.js
6025 error You can get information on how to open an issue for this project with:
6025 error     npm bugs phantomjs-prebuilt
6025 error Or if that isn't available, you can get their info via:
6025 error     npm owner ls phantomjs-prebuilt
6025 error There is likely additional logging output above.
6026 verbose exit [ 1, true ]

>

**Comment by viksit** [comment]
You need to make sure you have the latest npm and nodejs. Here's how I solved this:

```
sudo npm cache clean -f
sudo npm install -g n
sudo n stable

sudo ln -sf /usr/local/n/versions/node/<VERSION>/bin/node /usr/bin/nodejs

sudo npm install npm -g
```

and now, run `npm install` again.

**Comment by wenaro** [comment]
It solved problem for me, but you can also install  [extension](https://chrome.google.com/webstore/detail/elasticsearch-head/ffmkiejjmecolpfloofpjologoblkegm?hl=en-US) for Google Chrome. I think it is the easiest way to get web front panel for ES

**Comment by zhangqunshi** [comment]
After run npm install, I get the following errors:
```
npm ERR! Linux 4.13.0-36-generic
npm ERR! argv "/usr/local/n/versions/node/9.6.1/bin/node" "/usr/bin/npm" "install"
npm ERR! node v9.6.1
npm ERR! npm  v3.5.2
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'ansi'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/buaa/elasticsearch-head/npm-debug.log
```

**Comment by zhangqunshi** [comment]
I got the reason, because the npm is old version. Use the following command to upgrade npm:
```
npm install -g npm
```
The strange is when you run npm without sudo, then the version still is old.
```
npm -v
3.5.2
/usr/local/lib/node_modules/npm/bin/npm-cli.js -v
5.7.1
```

So don't run `npm install`, please run `sudo npm install`.

Good luck,
Kris
