### ISSUE TITLE
Empty page with no output

### ISSUE THREAD

**Issue by zopyx** [mobz/elasticsearch-head#338]
I installed 

```
git clone git://github.com/mobz/elasticsearch-head.git
cd elasticsearch-head
npm install
npm run start
open http://localhost:9100/
```

on two different systems.

Opening the URL in the browser only give me an empty page with the following HTML:

```

<!DOCTYPE html>

<html>
	<head>
		<meta charset="UTF-8">
		<title>elasticsearch-head</title>
		<link rel="stylesheet" href="_site/base/reset.css">
		<link rel="stylesheet" href="_site/vendor.css">
		<link rel="stylesheet" href="_site/app.css">
		<script src="_site/i18n.js" data-baseDir="_site/lang" data-langs="en,fr,pt,zh,tr,ja"></script>
		<script src="_site/vendor.js"></script>
		<script src="_site/app.js"></script>
		<script>
			window.onload = function() {
				if(location.href.contains("/_plugin/")) {
					var base_uri = location.href.replace(/_plugin\/.*/, '');
				}
				var args = location.search.substring(1).split("&").reduce(function(r, p) {
					r[decodeURIComponent(p.split("=")[0])] = decodeURIComponent(p.split("=")[1]); return r;
				}, {});
				new app.App("body", {
					id: "es",
					base_uri: args["base_uri"] || base_uri,
					auth_user : args["auth_user"] || "",
					auth_password : args["auth_password"],
					dashboard: args["dashboard"]
				});
			};
		</script>
		<link rel="icon" href="base/favicon.png" type="image/png">
	</head>
	<body></body>
</html>

```

**Comment by zopyx** [comment]
There is also this JS error

```
app.js:4183 Uncaught TypeError: this.statEl.text(...).css is not a function
    at Class.init (http://localhost:9100/_site/app.js:4183:64)
    at Class (http://localhost:9100/_site/app.js:265:28)
    at Class.init (http://localhost:9100/_site/app.js:4347:19)
    at Class.prototype.(anonymous function) [as init] (http://localhost:9100/_site/app.js:281:64)
    at Class (http://localhost:9100/_site/app.js:265:28)
    at window.onload (http://localhost:9100/:21:5)
```

**Comment by zopyx** [comment]
The problem seems to be specific to Chrome on Linux. Firefox on Linux works

**Comment by zhangweilun** [comment]
i face the problem too,and i change the web browser ,  then it is ok!  i

**Comment by zhangweilun** [comment]
@zopyx i face the problem too,and i change the web browser , then it is ok! i
