### ISSUE TITLE
Elasticsearch-head installation issue on server without connectivity

### ISSUE THREAD

**Issue by mori-ol** [mobz/elasticsearch-head#369]
Hello,

I am trying to install elasticsearch head. 
I am working on a machine with no internet access. What I have done installation of elasticsearch head on another server, which has internet access and then copy over the whole elasticsearch head folder, to the server without internet.
I followed the following directions and am trying to do now npm run start on my server without internet as per :
https://github.com/mobz/elasticsearch-head#running-with-built-in-server

sudo npm start

> elasticsearch-head@0.0.0 start /etc/elasticsearch-head-master
> grunt server

module.js:471
    throw err;
    ^

Error: Cannot find module 'grunt-cli/bin/grunt'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/etc/elasticsearch-head-master/node_modules/.bin/grunt:3:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Linux 3.10.0-514.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "start"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! elasticsearch-head@0.0.0 start: `grunt server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the elasticsearch-head@0.0.0 start script 'grunt server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the elasticsearch-head package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs elasticsearch-head
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls elasticsearch-head
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /etc/elasticsearch-head-master/npm-debug.log

My versions of nodejs and npm are below:
npm-3.10.10-1.6.9.4.2.el7.x86_64
nodejs-6.9.4-2.el7.x86_64 
I am on Centos 7.3

Any ideas how to fix this, on a server without internet?

**Comment by fendouxiong** [comment]
update your  npm   whit "npm i -g npm"

**Comment by nortrom-lh** [comment]
https://nodejs.org/en/download/
download the lastest node.js and npm。

version：node -v
